export const PL_CITIES: string[] = [
  'Warszawa',
  'Kraków',
  'Łódź',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Katowice',
  'Białystok',
  'Gdynia',
  'Częstochowa',
  'Radom',
  'Sosnowiec',
  'Toruń',
  'Kielce',
  'Rzeszów',
  'Gliwice',
  'Zabrze',
  'Olsztyn',
  'Bielsko-Biała',
  'Bytom',
  'Zielona Góra',
  'Rybnik',
  'Ruda Śląska',
  'Opole',
  'Tychy',
  'Gorzów Wielkopolski',
  'Dąbrowa Górnicza',
  'Elbląg',
  'Płock',
  'Wałbrzych',
  'Włocławek',
  'Tarnów',
  'Chorzów',
  'Koszalin',
  'Kalisz',
  'Legnica',
  'Grudziądz',
  'Jaworzno',
  'Słupsk',
  'Jastrzębie-Zdrój',
  'Nowy Sącz',
  'Jelenia Góra',
  'Siedlce',
  'Mysłowice',
  'Konin',
  'Piła',
  'Inowrocław',
  'Ostrów Wielkopolski',
  'Suwałki',
  'Zamość',
  'Ostrowiec Świętokrzyski',
  'Kędzierzyn-Koźle',
  'Przemyśl',
  'Stalowa Wola',
  'Tczew',
  'Trójmiasto',
];
